fix = true
indent-width = 4
line-length = 120
target-version = "py39"

[format]
docstring-code-format = true
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
# Like Black, use double quotes for strings.
quote-style = "double"
# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

[lint]
extend-select = [
  "UP",  # pyupgrade
  "LOG",  # flake8-logging
  "G",  # flake8-logging-format
  "I",  # isort
  "RUF010",  # Use explicit conversion flag
  "RUF013",  # PEP 484 prohibits implicit Optional
  "RUF015",  # Prefer next({iterable}) over single element slice
  "RUF017",  # Avoid quadratic list summation
  "RUF022",  # __all__ is not sorted
  "RUF100",  # unused-noqa"
  "T10",  # flake8-debugger
  "D"  # pydocstyle rules
]
ignore = [
  "D417",  # requires documentation for every function parameter.
  "D100",  # Missing docstring in public module
  "D101",  # Missing docstring in public class
  "D102",  # Missing docstring in public method
  "D103",  # Missing docstring in public function
  "D104",  # Missing docstring in public package
  "D105",  # Missing docstring in magic method
  "D106",  # Missing docstring in public nested class
  "D107"  # Missing docstring in __init__
]
preview = true

[lint.per-file-ignores]
# Do not enforce usage and import order rules in init files
"__init__.py" = ["E402", "F401", "I"]


[lint.pydocstyle]
convention = "google"
