services:

  events-pubsub:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      
  tweet-embedding-service:
    build:
      context: .
      dockerfile: Dockerfile.tweet_embedding_service
    depends_on:
      - events-pubsub
    environment:
      - REDIS_EVENTS_PUBSUB_ADDR=events-pubsub:6379
      - LANCEDB_TABLE_NAME=${LANCEDB_TABLE_NAME-tweets}
    volumes:
      - .env.dev:/app/.env.dev
      - ./data:/app/data

  agents:
    build:
      context: .
      dockerfile: Dockerfile.agents
    command: "uv run -m unhinged_twitter_bot --session-id my-sess-TODO-CHANGE"
    depends_on:
      - events-pubsub
      - tweet-embedding-service
    volumes:
      - ./data:/app/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

volumes:
  redis_data:
