FROM python:3.12-slim

WORKDIR /app

# Install dependencies
RUN pip install uv
COPY . /app
RUN uv sync --frozen --no-dev

# This is the location it will dump data into -- you should mount a volume here
RUN mkdir /app/dump

# Run the batch ingest subscriber
ENTRYPOINT ["uv", "run", "batch_ingest_subscriber", "/app/dump"]
